# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
      - develop

pool:
  vmImage : 'windows-latest'

stages:
  - stage: 'Build'
    displayName: 'Build .Net Web Application'
    variables:
      solution : '**/*.sln'
      buildplatform : 'Any CPU'
      buildconfiguration : 'Release'  
    pool:
      vmImage : 'windows-latest'
    jobs:
    - job: 'Build'
      displayName: 'Build Job'
      steps :
      - task : NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$solution'
      
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'   

  - stage: 'Deploy'
    displayName: 'Deploy the web application'
    dependsOn: Build
    jobs:
    - deployment: 'DeployToDev'
      displayName: 'Deploy the web application to dev environment'
      variables:
        Parameters.IISDeploymentType: 'IISWebsite'
        Parameters.ActionIISWebsite: 'CreateOrUpdateWebsite'
        Parameters.WebsiteName: 'Default Web Site'
        Parameters.WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\AspNetDemo'
        Parameters.AddBinding: false
        Parameters.VirtualPathForApplication: '/AspNetDemo'
        Parameters.AppPoolName: ''
        Parameters.VirtualApplication: 'AspNetDemo'
        Parameters.Package: '$(Pipeline.Workspace)\drop\*.zip'
        Parameters.RemoveAdditionalFilesFlag: true
        Parameters.TakeAppOfflineFlag: true
        Parameters.XmlTransformation: true
        Parameters.XmlVariableSubstitution: true
      environment:
        name: Dev
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop  
    

